---
title: "Homework_4"
author: "Alphonso Saiewane, Emmenta Janneh, Miles Matthews"
date: "2024-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# Question 1

## Part a
```{r}
nrow(iris)
```

## Part b (1)
```{r}
sepal_size <- map2_dbl(iris$Sepal.Length, iris$Sepal.Width, ~ .x * .y)
nrow(as_tibble(sepal_size))
```

## Part b (2)
```{r}
iris_cleaned <- iris%>%
  select(Sepal.Length)

x <- map_dbl(iris_cleaned$Sepal.Length, num)
nrow(as_tibble(x))
```

# Question 3

First tibble:

```{r}
rnorms_list <- list(negative_10 = c(rnorm(n = 10, mean = -10)),
                  zero = c(rnorm(n = 10, mean = 0)),
                  ten = c(rnorm(n = 10, mean = 10)),
                  hundred = c(rnorm(n = 10, mean = 100))
)


rnorms_tibble <- as_tibble(rnorms_list)
View(rnorms_tibble)
```

Second tibble:

```{r}
rnorms_list <- list(negative_10 = c(rnorm(n = 10, mean = -10)),
                  zero = c(rnorm(n = 10, mean = 0)),
                  ten = c(rnorm(n = 10, mean = 10)),
                  hundred = c(rnorm(n = 10, mean = 100))
)


rnorms_tibble <- as_tibble(rnorms_list)
View(rnorms_tibble)
```


Credit to https://www.geeksforgeeks.org/how-to-convert-a-list-to-a-dataframe-in-r/ for reference. 


