---
title: "HomeWork2_Week3"
authors: "Emmenta Janneh, Miles Matthews, and Alphonoso Saiewane"
date: "2024-02-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question 3

```{r}
#Original:
team_A <-2
team_B <- 2

if (team_A > team_B){
  print ("Team A won")
} else if (team_A < team_B) {
  print ("Team B won")
}else {
  print("Team A and B tied")
}

#Adjusted to show "Team A won":
team_A <-3
team_B <- 2

if (team_A > team_B){
  print ("Team A won")
} else if (team_A < team_B) {
  print ("Team B won")
}else {
  print("Team A and B tied")
}
```


# Question 4

## creating function
```{r}
num_sort <- function(val) {
if ((val %% 3) == 0) {
  if (val %% 5 == 0) {
    print ("divisible by Three and Five")
  } else if (val %% 4 == 0) {
    print ("divisible by Three and Four")
  } else {
      print ("neither")
    }
} else {
  print("neither")
}
}
```


## when val is 16
```{r}
num_sort(16)
```
## when val is 45
```{r}
num_sort(45)
```

## when val is 24
```{r}
num_sort(24)
```


# Question 5

## Creating modified mpg data table
```{r}
mpg2 <- mpg |>
  select(displ, cyl, cty, hwy)
mpg2
```

## Finding variances

```{r}
mpg_vars <- vector("double", ncol(mpg2))
for (i in seq_along(mpg2)) {
  mpg_vars[[i]] <- var(mpg2[[i]])
}
mpg_vars
```
